export { default as Home } from './Home'
export { default as Sound } from './Sound'
export { default as Legal } from './Legal'
export { default as Privacy } from './Privacy'
export { default as Error } from './Error'
